[package]
name = "launcher"
version = "0.1.0"
edition = "2024"

[dependencies]
fend-core = "1.5.8"
freedesktop-desktop-entry = "0.8.1"
iced = { version = "0.14.0", features = ["image"]}
iced_layershell = "0.14.2"
